name: CI
on:
  push:
    branches:
      - master
#      - aaron_dev

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false
        

    - name: Install and Build
      run: |
        yarn
        npm run build:prod
     

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.NSURE_WEBSITE_SECRET }}
        BRANCH: gh-pages
        FOLDER: dist/prod
